export const paths = {
  dashboard: "/",
  product: "/product",
  createProduct: "/product/create",
  category: "/category",
  createCategory: "/category/create",
  order: "/order",
  customer: "/customer",
  promotion: "/promotion",
  createPromotion: "/promotion/create",
  giveaway: "/giveaway",
  createGiveaway: "/giveaway/create",
  slidShow: "/slide-show",
  createSlideShow: "/slide-show/create",
  blog: "/blog",
  createBlog: "/blog/create",
  extraData: "/extra-data",
  createExtraData: "/extra-data/create",
  request: "/request",
  setting: "/setting",
};
